---
title: "Rachel Jakielski CS1675 Final Project"
output: html_document
---

***Test Set Predictions***

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
```

```{r, read_test_set}

set <- read.csv(file = 'cs_1675_fall2021_holdout_inputs.csv')
set
```

```{r, format_predictions}
test_set_regression <- set %>% 
      mutate(x5 = 1 - (x1 + x2 + x3 + x4),
                 w = x2 / (x3 + x4),
                 z = (x1 + x2) / (x5 + x4),
                 t = v1 * v2)  %>% glimpse()
```

```{r, import_models}
#Classification
xgb_tuned_class <- readr::read_rds("XGB_EXPANDED_TUNED_ACC.rds")

#Regression
xgb_tuned_reg <- readr::read_rds("XGB_EXPANDED_TUNED.rds")

```

```{r, make_preds_regression}
predict_xgb_reg<-predict(xgb_tuned_reg, test_set_regression)
```

```{r, make_preds_classification}
predict_xgb_class<-predict(xgb_tuned_class, test_set_regression, type = 'prob')

outcome = ifelse(predict_xgb_class$event>=1/2, 'event','not_event')

```

```{r, save_csv}
test_predictions <- data.frame(y = predict_xgb_reg, 
                               outcome = outcome,
                               probability = predict_xgb_class$event) %>% 
                               tibble::rowid_to_column("id") %>% 
                               readr::write_csv("test_predictions.csv")

```


